default:
  tags: [cpu]

stages:
   - linter
   - build
   - test
   - profile

# Define the workflow rules manually to make sure only a single pipeline
# is created for each MR update. Without that, GitLab creates one pipeline
# for branch update and one for MR update.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_DRAFT'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

# Enable when there is at least one .sh file.
.shell_check:
  image: koalaman/shellcheck-alpine:stable
  stage: linter
  dependencies: []
  before_script:
    - shellcheck --version
  script:
    - find . -type f -name '*.sh' -print0 | xargs -0 shellcheck -x

black:
  stage: linter
  image: python:3.10
  script:
    - pip3 install -U pip
    - pip3 install black==25.12.0 # The version here should be the same as in .pre-commit-config.yaml
    - black --check .

.prospector:
  stage: linter
  image: python:3.10
  script:
    - pip install prospector==1.14.0
    - prospector

secret_detection:
  stage: linter
  dependencies: []
  before_script: []
  image:
    name: zricethezav/gitleaks:v8.18.2
    entrypoint: [""]
  script:
    - gitleaks detect -v --source .


.build_config: &build_config
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/tcuscan/gdn-tri-inverse:8.5.0-19032026
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
    - export CMAKE_GENERATOR="Unix Makefiles" && pip3 install -v . --extra-index-url https://download.pytorch.org/whl/cpu

build:
  <<: *build_config
  tags:
    - docker_npu
  stage: build
  script:
    - echo "gdn-tri-inverse pip install succeeded!" || exit $?

test_tri_inv:
  <<: *build_config
  tags:
    - docker_npu
  stage: test
  script:
    - pytest tests/test_linalg.py

test_sgl_kernels_npu:
  <<: *build_config
  tags:
    - docker_npu
  stage: test
  script:
    - pytest tests/sgl_kernels_npu

# Test the Tilelang GDN inverse optimized implementation.
test_tilelang_opt_gdn:
  <<: *build_config
  tags:
    - docker_npu
  stage: test
  script:
    - source /workspace/tilelang-ascend/set_env.sh && python -m pytest tests/tilelang_opt_gdn


profile_tri_inv_910B4:
  <<: *build_config
  tags:
    - docker_npu
  stage: profile
  script:
    - . /workspace/tilelang-ascend/set_env.sh && make profile_tri_inv
  artifacts:
    expire_in: 1 hours
    paths:
      - bench_results_solve_tril*.csv
      - benchmark_tri_inv.log
      - profiling/nbs/figs/*.png
  when: manual
  allow_failure: true


profile_tri_inv_910B2:
  <<: *build_config
  tags:
    - docker_npu_910B2
  stage: profile
  script:
    - source /workspace/tilelang-ascend/set_env.sh && make profile_tri_inv
  artifacts:
    expire_in: 1 hours
    paths:
      - bench_results_solve_tril*.csv
      - benchmark_tri_inv.log
      - profiling/nbs/figs/*.png
  when: manual
  allow_failure: true


profile_gdn_layer:
  <<: *build_config
  stage: profile
  tags:
    - docker_npu_910B2
  script:
    - source /workspace/tilelang-ascend/set_env.sh && make profile_gdn_layer
  artifacts:
    expire_in: 1 hours
    paths:
      - bench_results_gdn*.csv
      - benchmark_gdn.log
  when: manual
  allow_failure: true

profile_tilelang_full_gdn:
  <<: *build_config
  stage: profile
  tags:
    - docker_npu_910B2
  script:
    - source /workspace/tilelang-ascend/set_env.sh && python profiling/bench_tilelang_full_gdn.py
  artifacts:
    expire_in: 1 hours
    paths:
      - bench_results_*.png
      - bench_results_*.csv
  when: manual
  allow_failure: true

analyze_tilelang_opt_solve_tril:
  <<: *build_config
  tags:
    - docker_npu_910B2
  stage: profile
  script:
    - source /workspace/tilelang-ascend/set_env.sh && python profiling/analysis_tilelang_opt_solve_tril.py
  artifacts:
    expire_in: 1 hours
    paths:
      - bench_results_*.png
      - bench_results_*.csv
  when: manual
  allow_failure: true
