default:
  tags: [cpu]

stages:
   - linter
   - build
   - test
   - profile

# Define the workflow rules manually to make sure only a single pipeline
# is created for each MR update. Without that, GitLab creates one pipeline
# for branch update and one for MR update.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_DRAFT'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

# Enable when there is at least one .sh file.
.shell_check:
  image: koalaman/shellcheck-alpine:stable
  stage: linter
  dependencies: []
  before_script:
    - shellcheck --version
  script:
    - find . -type f -name '*.sh' -print0 | xargs -0 shellcheck -x

black:
  stage: linter
  image: python:3.10
  script:
    - pip3 install -U pip
    - pip3 install black==25.12.0 # The version here should be the same as in .pre-commit-config.yaml
    - black --check .

.prospector:
  stage: linter
  image: python:3.10
  script:
    - pip install prospector==1.14.0
    - prospector

secret_detection:
  stage: linter
  dependencies: []
  before_script: []
  image:
    name: zricethezav/gitleaks:v8.18.2
    entrypoint: [""]
  script:
    - gitleaks detect -v --source .


.build_config: &build_config
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/tcuscan/gdn-tri-inverse:8.5.0-ef62c41
  tags:
    - docker_npu
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
    - pip3 install pyyaml setuptools pytest
    - pip3 uninstall triton -y && pip3 install --force-reinstall -i https://test.pypi.org/simple/ "triton-ascend<3.2.0rc" --pre --no-cache-dir
    - export CMAKE_GENERATOR="Unix Makefiles" && pip3 install -v . --extra-index-url https://download.pytorch.org/whl/cpu 

build:
  <<: *build_config
  stage: build
  script:
    - echo "gdn-tri-inverse pip install succeeded!" || exit $?

test_tri_inv:
  <<: *build_config
  stage: test
  script:
    - pytest tests/test_linalg.py

test_sgl_kernels_npu:
  <<: *build_config
  stage: test
  script:
    - pytest tests/sgl_kernels_npu


profile_tri_inv:
  <<: *build_config
  stage: profile
  script:
    - make profile_tri_inv
  artifacts:
    expire_in: 1 hours
    paths:
      - bench_results_solve_tril*.csv
      - benchmark_tri_inv.log
      - profiling/nbs/figs/*.png
  when: manual
  allow_failure: true
