default:
  tags: [cpu]

stages:
   - linter
   - build

# Define the workflow rules manually to make sure only a single pipeline
# is created for each MR update. Without that, GitLab creates one pipeline
# for branch update and one for MR update.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_DRAFT'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

# Enable when there is at least one .sh file.
.shell_check:
  image: koalaman/shellcheck-alpine:stable
  stage: linter
  dependencies: []
  before_script:
    - shellcheck --version
  script:
    - find . -type f -name '*.sh' -print0 | xargs -0 shellcheck -x

black:
  stage: linter
  image: python:3.10
  script:
    - pip3 install -U pip
    - pip3 install black==25.12.0 # The version here should be the same as in .pre-commit-config.yaml
    - black --check .

.prospector:
  stage: linter
  image: python:3.10
  script:
    - pip install prospector==1.14.0
    - prospector

secret_detection:
  stage: linter
  dependencies: []
  before_script: []
  image:
    name: zricethezav/gitleaks:v8.18.2
    entrypoint: [""]
  script:
    - gitleaks detect -v --source .


.build_config: &build_config
  tags:
    - baremetal
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
    - pip3 install pyyaml setuptools pytest
    - pip3 install https://gitcode.com/Ascend/pytorch/releases/download/v7.3.0-pytorch2.8.0/torch_npu-2.8.0.post2-cp310-cp310-manylinux_2_28_x86_64.whl --index-url https://download.pytorch.org/whl/cpu # https://github.com/sgl-project/sgl-kernel-npu/pull/326


run_pto_isa_add_kernel:
  <<: *build_config
  stage: build
  script:
    - cd pto-isa-tri-inv/
    - pip3 install -r requirements.txt
    - git clone https://gitcode.com/cann/pto-isa.git PTO_ISA_ROOT
    - pip install -U setuptools packaging
    - bash run.sh
    - python3 -m pytest -v tests/test_abs.py

run_pto_isa_tri_inv_kernel:
  <<: *build_config
  stage: build
  script:
    - cd pto-isa-tri-inv/
    - pip3 install -r requirements.txt
    - git clone https://gitcode.com/cann/pto-isa.git PTO_ISA_ROOT
    - pip install -U setuptools packaging
    - bash run.sh
    - python3 -m pytest -v tests/test_tri_inv_col_sweep.py

run_pto_isa_simple_matmul_kernel:
  <<: *build_config
  stage: build
  script:
    - cd pto-isa-tri-inv/
    - pip3 install -r requirements.txt
    - git clone https://gitcode.com/cann/pto-isa.git PTO_ISA_ROOT
    - pip install -U setuptools packaging
    - bash run.sh
    - python3 -m pytest -v tests/test_simple_matmul.py

run_pto_isa_batch_matrix_square_kernel:
  <<: *build_config
  stage: build
  script:
    - cd pto-isa-tri-inv/
    - pip3 install -r requirements.txt
    - git clone https://gitcode.com/cann/pto-isa.git PTO_ISA_ROOT
    - pip install -U setuptools packaging
    - bash run.sh
    - python3 -m pytest -v tests/test_batch_matrix_square.py