[project]
name = "gdn-tri-inverse"
version = "0.1.0"
description = ""
authors = [
    {name = "\"GDN Triangular Inverse Team\""}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "torch>=2.10.0",
  "torch-npu>=2.10.0",
  "triton-ascend>=3.2.1",
  "pto_kernels>=0.1.4",
]

[project.optional-dependencies]
kernels = [
  "sgl-kernel-npu",
]

[tool.pip]
extra-index-url = ["https://download.pytorch.org/whl/cpu", "https://test.pypi.org/simple/"]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
